Rtl chart upgrade
GaloyMoney/charts pull request #886
Opened 2022-04-28 13:56 UTC by zoop-btc

This PR changes the configuration map to iterate over an array of lnd values. I have also added the possibility to enable dark mode and themes.
I've also set the channelBackupPath to a place where the rtl process has write access - else you get error messages with each channel open or close.
Additionally I have added an optional standard ingress template.

2022-05-03 07:54 UTC, bodymindarts commented
It looks good except for the ingress. Exposing RTL on the internet is pretty bad from a security POV and I don't think its something we should support OOTB.

2022-05-18 07:25 UTC, zoop-btc commented
@bodymindarts I removed the ingress and cleaned up the pull request.

2022-06-06 10:41 UTC, zoop-btc commented
> @zoop-btc this would be nice to squash those commits

yes sorry, I wanted to bring this branch up to speed and it somehow added all the commits as new ones

fixed now

2022-07-11 11:07 UTC, krtk6160 requested changes
@zoop-btc I have tested this locally and it works perfectly! Thank you for the PR. Just a couple of nits around naming, but otherwise LGTM

2022-07-11 11:07 UTC, krtk6160 commented on charts/rtl/values.yaml
> +    secretname: lnd1-credentials
```suggestion
    secretName: lnd1-credentials
```

2022-07-11 11:07 UTC, krtk6160 commented on charts/rtl/values.yaml
> +lnd:
```suggestion
lnds:
```

2022-07-11 16:57 UTC, zoop-btc commented on charts/rtl/values.yaml
> +    secretname: lnd1-credentials
Renamed according to suggestion.

2022-07-11 16:59 UTC, zoop-btc commented
@krtk6160 done, adjusted the values, configmap and deployment accordingly

2022-07-12 08:51 UTC, krtk6160 approved these changes

2022-07-12 11:23 UTC, merged